### ISSUE TITLE
please rename this to epikapi

### ISSUE THREAD

**Issue by Epikest** [nickk431/Lunar#1]

**Comment by nickk431** [comment]
why!!!!

**Comment by Epikest** [comment]
because that was the name of the project you stole from :trollface:

**Comment by nickk431** [comment]
nope i have permission from hunter to use epikapi uwu

**Comment by Epikest** [comment]
where is hunter then

**Comment by nickk431** [comment]
idk! probably working at taco bell still 😔

**Comment by Epikest** [comment]
no, how did you contact him?

**Comment by nickk431** [comment]
we were pretty good friends before he quit, some of the functions were made for me

**Comment by Epikest** [comment]
so you talked to him irl?

**Comment by nickk431** [comment]
no, i havent talked to him since he quit everything

**Comment by Epikest** [comment]
dang, you got discord?

**Comment by Toon-arch** [comment]
proof when

**Comment by nickk431** [comment]
nickk#5538

**Comment by Toon-arch** [comment]
https://discord.gg/mVzBU7GTMy

**Comment by Toon-arch** [comment]
join

**Comment by Epikest** [comment]
bruh advertising

**Comment by Toon-arch** [comment]
fym

**Comment by Toon-arch** [comment]
it's ur server :bigsad:

**Comment by Toon-arch** [comment]
our server trol
